CREATE TABLE PERSON( 
PERSON_ID INTEGER     NOT NULL,
NAME      VARCHAR(20) NOT NULL,
SURNAME   VARCHAR(20) NOT NULL,
CONSTRAINT pk_per_pid PRIMARY KEY (PERSON_ID));


CREATE SEQUENCE seq_person_pid
START WITH 1000
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER tri_person_pid 
 BEFORE INSERT  ON PERSON
 FOR EACH ROW  
  BEGIN    
    SELECT seq_person_pid.nextval    INTO :new.PERSON_ID    FROM dual;  
 END;
/


CREATE TABLE PROFESSOR(
PERSON_ID INTEGER PRIMARY KEY,
SALARY FLOAT,
CONSTRAINT professor_fk_person FOREIGN KEY (person_id) REFERENCES PERSON (person_id)
);